## Productionisation (Model Deserialization)

In [1]:
import numpy as np
from pickle import load

In [5]:
# Loading pretrained classifiers from pickle file

scaler = load(open('D:\github\MLOPs\models\standard_scaler.pkl', 'rb'))
knn_classifier = load(open('D:\github\MLOPs\models\knn_model.pkl', 'rb'))
lr_classifier = load(open('D:\github\MLOPs\models\lr_model.pkl', 'rb'))

dt_classifier = load(open('D:\github\MLOPs\models\dt_model.pkl', 'rb'))
sv_classifier = load(open('D:\github\MLOPs\models\sv_model.pkl', 'rb'))

In [6]:
# Read the Query Data

print("Enter Iris Flower Details")
sl = float(input('Enter the SepalLength (in cm): '))
sw = float(input('Enter the SepalWidth (in cm): '))
pl = float(input('Enter the PetalLength (in cm): '))
pw = float(input('Enter the PetalWidth (in cm): '))

Enter Iris Flower Details
Enter the SepalLength (in cm): 5.1
Enter the SepalWidth (in cm): 3.0
Enter the PetalLength (in cm): 1.1
Enter the PetalWidth (in cm): 0.1


## Converting the values to 2D Array

In [7]:
#Converting it into 2D array because it will thrown an error if we work on 1D array

In [8]:
query_point = np.array([sl, sw, pl, pw])

In [9]:
query_point

array([5.1, 3. , 1.1, 0.1])

In [10]:
query_point.reshape(1, -1)

array([[5.1, 3. , 1.1, 0.1]])

In [12]:
query_point = query_point.reshape(1, -1)

query_point

array([[5.1, 3. , 1.1, 0.1]])

In [13]:
query_point_transformed = scaler.transform(query_point)

query_point_transformed

C:\Users\ani\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-0.90683992, -0.11925475, -1.50416612, -1.44042398]])

In [14]:
knn_classifier.predict(query_point_transformed)

C:\Users\ani\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array(['Iris-setosa'], dtype=object)

In [15]:
lr_classifier.predict(query_point_transformed)

C:\Users\ani\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array(['Iris-setosa'], dtype=object)

In [17]:
dt_classifier.predict(query_point_transformed)

C:\Users\ani\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array(['Iris-setosa'], dtype=object)

In [18]:
sv_classifier.predict(query_point_transformed)

C:\Users\ani\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array(['Iris-setosa'], dtype=object)

## Production Ready Code

In [19]:
# Read the Query Data

print("Enter Iris Flower Details")
sl = float(input('Enter the SepalLength (in cm): '))
sw = float(input('Enter the SepalWidth (in cm): '))
pl = float(input('Enter the PetalLength (in cm): '))
pw = float(input('Enter the PetalWidth (in cm): '))

query_point = np.array([sl, sw, pl, pw]).reshape(1, -1)

query_point_transformed = scaler.transform(query_point)

knn_classifier.predict(query_point_transformed)

Enter Iris Flower Details
Enter the SepalLength (in cm): 5.1
Enter the SepalWidth (in cm): 3.0
Enter the PetalLength (in cm): 1.1
Enter the PetalWidth (in cm): 0.1


C:\Users\ani\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\ani\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array(['Iris-setosa'], dtype=object)